name: Test meson build
on:
  push:
    branches: [ main ]
  pull_request:	
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v2

      - name: Add user
        run: |
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Install Packages
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf

          pacman -Syu --noconfirm \
            git \
            base-devel \
            meson \
            ninja \
            sudo \
            lib32-gnutls \
            gtksourceview3 \
            gtksourceview4 \
            hicolor-icon-theme \
            dconf \
            python \
            libhandy \
            gtk3 \
            p7zip \
            python-gobject \
            python-requests \
            python-yaml \
            python-markdown \
            python-pip \
            cabextract \
            webkit2gtk \
            xorg-xdpyinfo \
            blueprint-compiler

          pip install patool
       

      - name: Build
        run: |
          chown user -R .
          chmod +x install.sh
          su user -c "./install.sh"
