on:
  push:
    branches: [main]
  pull_request:
name: Build Flatpak
jobs:
  flatpak:
    name: "build-packages"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - name: "remove-urls"
      run: |
        sed '/.*vcs-browser.*/d' -i data/com.usebottles.bottles.appdata.xml.in
        sed '/.*contribute.*/d' -i data/com.usebottles.bottles.appdata.xml.in
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: bottles.flatpak
        manifest-path: com.usebottles.bottles.dev.yml
        cache-key: flatpak-builder-${{ github.sha }}