name: Build unstable packages
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # Dependencies
      # --------------------------------------
      - name: Install build dependencies
        run: |
          sudo apt update && sudo apt install -y debhelper python3 python3.8-minimal python3-pip python3-setuptools gettext build-essential patchelf librsvg2-dev desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace ninja-build meson winbind python3-yaml python3-requests flatpak-builder

      # Fix python interpreter
      # --------------------------------------
      - name: Fix python interpreter
        run: sed -i -e 's|@PYTHON@|/usr/bin/python3|g' src/bottles.in

      # AppImage Build
      # --------------------------------------
      - name: Install appimagetool
        run: |
           sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
           sudo chmod +x /usr/local/bin/appimagetool

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install appimage-builder tool
        run: yes | sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git

      - name: Build AppImage
        run: appimage-builder --recipe AppImageBuilder.yml --skip-test

      # Deb Build
      # --------------------------------------
      - name: Build .deb package
        run: dpkg-buildpackage


      # Flatpak
      # --------------------------------------
      - name: Build flatpak
        run: |
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak-builder --user  --force-clean --repo=repo --install-deps-from=flathub flatpak com.usebottles.bottles.dev.json
          flatpak build-bundle repo com.usebottles.bottles-unstable.flatpak com.usebottles.bottles --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

      # Rename and release packages
      # --------------------------------------
      - name: Rename packages
        run: |
          mv Bottles-*-x86_64.AppImage Bottles-devel-x86_64.AppImage
          mv Bottles-*-x86_64.AppImage.zsync Bottles-devel-x86_64.AppImage.zsync
          mv ../com.usebottles.bottles*.deb com.usebottles.bottles-unstable.deb

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: unstable
          title: Unstable build
          files: |
            Bottles-*-x86_64.AppImage*
            com.usebottles.bottles-unstable.deb
            com.usebottles.bottles-unstable.flatpak
