on:
  pull_request:
name: Mypy
jobs:
  pylint-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        sudo apt install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
        sudo apt install -y libcurl4-openssl-dev libssl-dev
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install mypy
        pip install -r requirements.txt
        pip install pycairo
        pip install PyGObject
        yes | mypy --install-types
    - name: Run mypy analysis
      id: pylint-result
      run: |
        mypy --version
        mypy bottles